// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollOff_Test4API.Data;

namespace RollOff_Test4API.Migrations
{
    [DbContext(typeof(RollOff4DbContext))]
    [Migration("20230301093433_FormUpdate")]
    partial class FormUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RollOff_Test4API.Models.Domain.Employee", b =>
                {
                    b.Property<double>("GlobalGroupId")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EmployeeNo")
                        .HasColumnType("float");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewGlobalPractice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleManagerPerformanceReviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Practice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProjectCode")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PspName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlobalGroupId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RollOff_Test4API.Models.Domain.FormTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Communication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EmployeeNo")
                        .HasColumnType("float");

                    b.Property<double>("GlobalGroupId")
                        .HasColumnType("float");

                    b.Property<string>("Labour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongLeave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpsFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Practice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimarySkill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProjectCode")
                        .HasColumnType("float");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForRollOff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RelevantExperienceYrs")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCompetencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RollOffEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RollOffStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThisReleaseNeedBackfillIsBackFilled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderProbation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalGroupId");

                    b.ToTable("FormTables");
                });

            modelBuilder.Entity("RollOff_Test4API.Models.Domain.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("login");
                });

            modelBuilder.Entity("RollOff_Test4API.Models.Domain.FormTable", b =>
                {
                    b.HasOne("RollOff_Test4API.Models.Domain.Employee", "Employees")
                        .WithMany()
                        .HasForeignKey("GlobalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
