export interface Form {
  globalGroupId : number,
    name : string,
    practice : string,
    performanceIssue : string,
    technicalSkills : string,
    localGrade : string,
    rollOffEndDate : Date,
    resigned : string,
    communication : string,
    primarySkills : string,
    reasonForRollOff : string,
    underProbation : string,
    roleCompetencies : string,
    projectCode : number,
    longLeave : string,
    remarks : string,
    projectName : string,
    thisReleaseNeedBackfillIsBackFilled : string,
    relevantExperienceInYears : string,
    leaveType : string,
    otherReasons : string,
    labour: string,
    requestDate: Date,
    status: string
}
